### ISSUE TITLE
change display listing of history in Appdaemon app/restore_state

### ISSUE THREAD

**Issue by Mariusthvdb** [azogue/hassio_config#1]
Hope this is the correct repo then...

coming from https://github.com/azogue/eventsensor/issues/11

about the Appdaemon app you created before. It is working beatifully, with 1 minor issue:
<img width="360" alt="Schermafbeelding 2020-04-30 om 11 32 55" src="https://user-images.githubusercontent.com/33354141/80695867-d20e2c00-8ad6-11ea-999d-5262acdb5b85.png">

Could it be listing the history 10 at the bottom? Preferably without adding a leading 0 to history 1-9. Like the original 'variable' solution I used:
<img width="365" alt="Schermafbeelding 2020-04-30 om 10 07 46" src="https://user-images.githubusercontent.com/33354141/80689583-d84bda80-8acd-11ea-83e2-d8cdde8e4709.png">

secondly:

is it possible to have this sensor.last_motion be restored at startup? right now, it isn't created at startup showing the empty bar in Lovelace. The variable.last_sensor is recorded in core.restore_state, but the sensor.last_motion created by this AD app isn't.

Thanks if you can find a moment to check, and again sorry for creating this issue in the wrong repo...

cheers,
Marius

**Comment by azogue** [comment]
> It is working beatifully, with 1 minor issue:

It is not the sensor fault, it looks like it's related to your python version/environment, can't help you with that. For me the order is fine:

<img width="367" alt="last_motion_sensor" src="https://user-images.githubusercontent.com/9748301/80795066-c8023100-8b9b-11ea-98c2-f34fd4f3ac8d.png">

> The variable.last_sensor is recorded in core.restore_state, but the sensor.last_motion created by this AD app isn't.

AppDaemon does not use the HA entity infraestructure, it uses the HA API. When it publishes new entities it's like if you do it manually with a POST to HA. There are [ways to achieve persistency](https://appdaemon.readthedocs.io/en/dev/AD_API_REFERENCE.html#appdaemon.adapi.ADAPI.save_namespace) in AD, but they require a more complex app for that (I don't plan to work on that)

**Comment by Mariusthvdb** [comment]
> It is not the sensor fault, it looks like it's related to your python version/environment
thanks for answering.

could it be you use AD 4? I am still using version 3 because of an other app, that wont run on 4...

**Comment by azogue** [comment]
I use AD 4, but not sure if it's related (don't think so). Anyway, not an issue, so  closing this :)
